table Details
	lineageTag: 77b8b7d7-7313-461d-b83c-be6d1339aa6c

	measure 'Info Tooltip' = "https://imagizer.imageshack.com/img923/4052/lLHy3U.gif"
		lineageTag: f155eadd-b274-4883-b283-c96badb87ab2
		dataCategory: ImageUrl

	measure 'Info Tooltip 2' = "https://imagizer.imageshack.com/img921/2483/uMs9ZQ.gif"
		lineageTag: 2f1ae8dc-8b8a-4688-ac37-30688be5c5b4

	column 'Design Factor'
		dataType: string
		lineageTag: 3cdc4098-d718-4b8d-9a58-baba27891e7b
		summarizeBy: none
		sourceColumn: Design Factor
		sortByColumn: DFSort

		annotation SummarizationSetBy = Automatic

	column DFSort
		dataType: int64
		formatString: 0
		lineageTag: fba7ec27-55d3-448e-87cc-85b90d9cc35f
		summarizeBy: sum
		sourceColumn: DFSort

		annotation SummarizationSetBy = Automatic

	column Topic
		dataType: string
		lineageTag: 46dcdfc1-b5a3-4eaf-839b-71316ce3827f
		summarizeBy: none
		sourceColumn: Topic
		sortByColumn: TSort

		annotation SummarizationSetBy = Automatic

	column TSort
		dataType: int64
		formatString: 0
		lineageTag: deac7728-e9d6-4591-87b8-0d25668a8006
		summarizeBy: sum
		sourceColumn: TSort

		annotation SummarizationSetBy = Automatic

	partition Details-a325cc9e-ad76-41a3-ab77-56cf74f9ea9d = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("lVXbcpswEP0VDc/OxMF2mjzKgBtNsWEwzmXSPChY2JrIKCNEU/ep39JP65dUK18mDYEQZjxjpLO7hz1npft7By98Esy8wOk5Z+YXxUGCUxLNcGjeXOehV4Ngs3eXEs8iBhYRhzidRMnUhvScOLoJEjQmyA/m39IoNkvD93Bo/yTsWSqNrjl7QWZ51JpzGo1JCFwuOqScykcu2DHzpQ1ZkNPFreXec0J8Fy1S+LJ+be+Qy5NFyUvNCo1CupWVBvhZDe5FYZTAltuYacozJUuZa5NTSFUCetCIvuKrNRTXipa25rAGHSd45pPZV9gddSgb5TnPOBUoVnJZZdoyOP9MYChX0kZ9qUWRWRokE7wzykVjUlLoimv+gwGsrsix64JRhXyqKfJN9xV/rDSXBehclyq4Nb49mNSta3NsqXw5SSVgmkXyqBBIS4SzQ71miaa84JtqY8jy7Ana4tY1MszAoHhPrlkmz/S6PIkF1blUG8A2K5MwIx9bGkMaX2ZbAO8EsdM5J3M7cz1nEuB0kQRz9L3q991z5OEYm/khKQkA4l68F3Qo4ituWjGVS5DKvfwQqtdKVqs1UO23gVMphebPgDtrw+2fv7//IJ/ltBIwBQO3Y8j+CIjpCugPBm1h17ysjLmvGF0yBehhxyL7T0Ep+2nJjT4Z94bkeVv4zZpqRHLAvav1AYcLKra/bL5WeV/RIUWmGC3Zqc92fyC4VfBXwRNeLA05phjSa17+N67Ivue52SygQcNWY0y40EyZbhRAYNhqjrGUTxuqnmC5qyUMs2dBt2jOBMu0GZ+d7hDQag9zCC85fI7xyMTMJtWaFysAdfWJPcfsoQ+Yzi7hWthOtPribZkxtTfL8GOTaJ5ZZFebwE2oKdyDfKdQZ4tIxbLdLTYyDnj4Bw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type text) meta [Serialized.Text = true]) in type table [#"Design Factor" = _t, DFSort = _t, Topic = _t, TSort = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"DFSort", Int64.Type}, {"TSort", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_QueryRelationships = {"columnCount":4,"keyColumnNames":[],"queryRelationships":[],"columnIdentities":["Section1/Details/Source.{Design Factor,0}","Section1/Details/Changed Type.{DFSort,1}","Section1/Details/Source.{Topic,2}","Section1/Details/Changed Type.{TSort,3}"],"ColumnCount":4,"KeyColumnNames":[],"ColumnIdentities":["Section1/Details/Source.{Design Factor,0}","Section1/Details/Changed Type.{DFSort,1}","Section1/Details/Source.{Topic,2}","Section1/Details/Changed Type.{TSort,3}"],"RelationshipInfo":[]}

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

