table Age
	lineageTag: 756a4221-6d25-4fb0-9d7d-d986aa24b623

	column Age
		dataType: int64
		formatString: 0
		lineageTag: 887da848-8581-4f2b-8c70-ff792e9615c7
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column 'Age Bucket'
		dataType: string
		lineageTag: 50f3568b-3688-4f7c-9f37-64a6882a1f34
		summarizeBy: none
		sourceColumn: Age Bucket

		annotation SummarizationSetBy = Automatic

	partition Age-3e4824bd-a87e-4e01-bfbf-166592b94c64 = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("dc8rDsAgEIThqxA0AnZZHmchCER1k7amty+gaMKYEZ/6pxTtRJs+6jkVWfUe7bp1Nd0D8Ag8Ac97JwvcdSc3XVYn4AzcAxfg4y+F4fzricAT8Lx3tsDHX549vPYwAWfgHrhsvH4=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type text) meta [Serialized.Text = true]) in type table [Age = _t, #"Age Bucket" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Age", Int64.Type}, {"Age Bucket", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

