table Product
	lineageTag: ff53b2a2-4c55-4f0e-ab71-65658d63edde

	column Product
		dataType: string
		lineageTag: 141b49c4-bc58-4b10-a645-ed5121833bdb
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column ProductID
		dataType: int64
		formatString: 0
		lineageTag: 82473cb8-4146-4f8a-aa18-86a80d1d980c
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: a667aa8a-42b9-4abe-b385-d17520b6caf7
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column CategoryID
		dataType: int64
		formatString: 0
		lineageTag: 55844161-5c57-4ae8-8b42-dd17d8dacc45
		summarizeBy: count
		sourceColumn: CategoryID

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 0d382620-d117-4bb1-af91-fea52261ed45
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column SegmentID
		dataType: int64
		formatString: 0
		lineageTag: f0af6567-e3b0-4b8b-9de5-7270c09378dd
		summarizeBy: count
		sourceColumn: SegmentID

		annotation SummarizationSetBy = Automatic

	column 'Product Image'
		dataType: string
		lineageTag: 8add36d7-a4fc-4919-914d-8b90310f5f11
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: Product Image

		annotation SummarizationSetBy = Automatic

	column 'Category Image'
		dataType: string
		lineageTag: 5853461a-ef63-4ab4-8433-2d54f00bf8df
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: Category Image

		annotation SummarizationSetBy = Automatic

	column 'Segement Color'
		dataType: string
		lineageTag: b94f9872-0fdd-4fba-b3a7-cbcfd8c5544e
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: Segement Color

		annotation SummarizationSetBy = Automatic

	column 'Segment image'
		dataType: string
		lineageTag: ffad2add-bc04-4d34-8bec-de4aaefa7c8c
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: Segment image

		annotation SummarizationSetBy = Automatic

	column Price
		dataType: int64
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 156de3a2-c60d-492a-b8b6-e3554526ac32
		summarizeBy: sum
		sourceColumn: Price

		annotation SummarizationSetBy = User

	column 'Price Range'
		dataType: string
		lineageTag: e2dda4cb-1802-4299-b686-7fd8eb0bb364
		summarizeBy: none
		sourceColumn: Price Range

		annotation SummarizationSetBy = Automatic

	partition Product-9f1e37c0-cc3c-40e9-b0aa-e33d9a0f7edc = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("xZlbU+JKEMe/imXt4+72ZC65nDcuwopCooAG9+xDhAEiIYFcUPj0ZwZxq04lW0UrWz4AIanBmV/9u/vf7c+f57XxWGbZ+ddzQ73c6TQcyzNmisONWzlR75Z6zfN8lf0DEC6DWbiT6Xd9IbN5MF58HydLdX/mUAoWowxYNiw6/vdVPDt2oQFUWAReLo3gKsYtdJgwwZ/vltdzzEIOnBEL/IF3wdhhoSDq7QsnZ9/Ovljk/NfXn+cXL2MZqbu0ik4nmEj1wY/HYwtHwLZ2PSEWZrMMTGFaENV/pCmSq6C2BfWXvvTu/g6eeRDPNAVWRaixDeLD5ZH7tZlgMBzE1m0NuV/DsYBGuS8SHFqHCg43IrBb0V8g5Mayl+RvMikB6qofjvNAXdnHq8jkFoPH0ct6scKJwbbVUZ+ajfVmizuqyYgNu2S6uUFFZxUjRx/034IQJn8zKvIoSRYa4ClExMHi1IaUR/MFSkRaC5Y6Z+HW2r1PA8Ttkoi85FmmXhLGuXpkVjFy00MYmsfLyDFsGN8+bYtnzJYpCFOR6sh2R2ZISIQbcPGUT9rso5BsUlKRVzxGYTaX6aFilRgNinRdJGH2lq2OPC5jnMHWn8otxXEyDdsBLtru3MGFqQpvBnGcLy47H+YkSpz68yCVb2KyTwaKgU2YBSzcxA83uPMawrCg77aKtvg0UGY5dfcX25VG4JwmKdnENGBN89YcuVnTsQU0zHbH739eUhIlPHdhFiYaAal0jsk2iM7qUSEP7ulYo2PZHLxCNC9RQaOslUFM6BGzNTaQ6Ywp2V4NZ+mPD9d/XhbRfZJqC21U2+t3QVKZm5ocwsFktOkiUxJ1YDhdT3yUizwpI6ucuf2662simsDhWqeddipljPPXDoXu3fXDCCUB1XyYjgkX7qB3E2AjzITheOI9LnE8qVrXMNPM7f1ZOco5NtNwo6VhVJprrG50ATZMWBRB3LlGNlmOcpzS9xcP409LQey3cRwrUHtEo2C53Nd7o9JcvyewtEvuxh5HBRYHw1H9Wf3+ub1rfR4gWgKko+nM7V1oIOLD0UWJJSATt5NZjuw7uLBgSu3WGIn1b8bX3lSf1S81G+2aX797UZBPk3R5oDSSUZQ8HzqTow0jERBNRlFjgDutan0NWDQv2WSDOy5XfQtMdhub2Mi/yGyYssud9/hnv3gVhLsg0i2qUWmr8T2+Y6jt+q77coXqshgY2lGncbJ20Xn6ZFFW0eMrzcTxax6q9NPYOZEe93ACV9vuHUF5RbWQKgkVsr99Qg2YTjonomYpD7VURO2HjJVe+l39hgGMKvcfDBcDnuLCxXIEgel4MWNPn9ZvUFKCtE9AtdUqe3tcykg6wXffMzGiWhtcsvkFcrq6b1qWs8hxZ0g92Q6DxOsOot0HUxIry2kgg72caKWr9op0Fb01bkfGDVXNOrhZcIezjoqsYakS1WNOiCptChCxTaiNBs0WsiZWaKnsjPp5qhjpZ5WTa+RcXzWvVBnAWer7HirWmFqoSv99XTYbyBIuVDGD0ZXkg9GH+fCygpJvTd280kpn/b6+TOUHrhJL4+l6fT3F7dlRUZbZtV0fNdA9aV/GWDlrv1qfPb7KXNSTSYzGxJWPJAS2de/+DlXG9XhWh2pv+Zgh/wtiOdyB2XAtQ2T/UspG1Pk/pl//AQ==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type text) meta [Serialized.Text = true]) in type table [Product = _t, ProductID = _t, Category = _t, CategoryID = _t, Segment = _t, SegmentID = _t, #"Product Image" = _t, #"Category Image" = _t, #"Segement Color" = _t, #"Segment image" = _t, Price = _t, #"Price Range" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Product", type text}, {"ProductID", Int64.Type}, {"Category", type text}, {"CategoryID", Int64.Type}, {"Segment", type text}, {"SegmentID", Int64.Type}, {"Product Image", type text}, {"Category Image", type text}, {"Segement Color", type text}, {"Segment image", type text}, {"Price", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

