table Calendar
	lineageTag: c345a94a-95e9-4d2f-9f82-5f10cdf2e21d

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: af6a8328-4a36-4f01-930d-b56aa3e62925
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 677d2c0d-f04e-4bfb-ab65-d6e85634f934
			defaultHierarchy: LocalDateTable_d9fbe243-4814-4038-8eec-593e864a563b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Month
		dataType: string
		lineageTag: 197cbcaf-4883-481b-9275-0fb20535bbf8
		summarizeBy: none
		sourceColumn: Month
		sortByColumn: MonthSort

		annotation SummarizationSetBy = Automatic

	column MonthSort
		dataType: int64
		formatString: 0
		lineageTag: ca435b58-13cf-451d-8a04-fcbc9d7a7a39
		summarizeBy: sum
		sourceColumn: MonthSort

		annotation SummarizationSetBy = Automatic

	column Week
		dataType: int64
		formatString: 0
		lineageTag: 309c3071-775d-4b59-96f3-a2746177525d
		summarizeBy: sum
		sourceColumn: Week

		annotation SummarizationSetBy = Automatic

	column Empty = ""
		lineageTag: 9e67d89a-f6e2-4f23-b0c2-78aedc214216
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Calendar-e63c2b10-f169-4be4-bbe5-8ec70193c03b = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("fZSxisMwDIZfJWQuqSQ7dtztlg6FPkHpkIMbrxyFG+7tq4vcwD9I4IQUvg/kfk5ut5H4qEuI28ByItI1rNPwPY2HkfW6rI/+xOP9oHzxeQFeNp6Tzyfg08YL+XwGPhtffX4Gfrb5dR5x+KLX+euz76TY/OTzFfhqfPX5BfjF5s8+34Bv+/zJ60V6u67P/tfqz/cOXIPR4H0PriFoyL4L10hoWOfEgZHRsNKkU2XP+E/98fPsh4StNefAKGhYbeHAqGhYb1kCY0HDitN81OUYbdv5Xz+8bM1ZfEMIDOnNW2AwGtZcSmAIGtZcj61+DBxje7V/H/2lEmtOLTAyGtacS2DMaFhzSYFR0LDmiQKjoqHN7y8=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type text) meta [Serialized.Text = true]) in type table [Date = _t, Week = _t, #"Month Name" = _t, MonthSort = _t, #"Week of Year" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Date", type datetime}, {"Week", Int64.Type}, {"Month Name", type text}, {"MonthSort", Int64.Type}, {"Week of Year", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Month Name", "Month"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"Date", type date}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type1",{"Week of Year"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

